{
 "title": "Frontend Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "listStudents Mean",
   "type": "graph",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Seconds" }
   ],
   "targets": [
    {
     "expr": "application_listStudentsTime_mean_seconds",
     "legendFormat": "Mean duration of listStudents call"
    }
   ]
  },
  {
   "title": "Number of Students",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 7, "x": 5, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "application_numberOfStudents" }
   ]
  },
  {
   "title": "listStudents Mean",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 5, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "application_listStudentsTime_mean_seconds"
    }
   ]
  },
  {
   "title": "listStudents Fallback",
   "type": "graph",
   "gridPos": { "h": 5, "w": 7, "x": 17, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Number of Calls" }
   ],
   "targets": [
    {
     "expr": "application_ft_org_acme_FrontendResource_listStudents_fallback_calls_total",
     "legendFormat": "Number of listStudents Fallback Calls"
    }
   ]
  },
  {
   "title": "Frontend /list Calls",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short", "label": "Number of Calls" }
   ],
   "targets": [
    {
     "expr": "application_listStudentsTime_seconds_count"
    }
   ]
  },
  {
   "title": "List Students Circuit Breaker",
   "type": "graph",
   "description": "Graphs time spent in each circuit breaker states",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "short", "label": "Seconds" }
   ],
   "targets": [
    {
     "expr": "application_ft_org_acme_FrontendResource_listStudents_circuitbreaker_closed_total/10000000000",
     "legendFormat": "Closed"
    },
    {
     "expr": "application_ft_org_acme_FrontendResource_listStudents_circuitbreaker_halfOpen_total/10000000000",
     "legendFormat": "Half-Open"
    },
    {
     "expr": "application_ft_org_acme_FrontendResource_listStudents_circuitbreaker_open_total/1000000000",
     "legendFormat": "Open"
    }
   ]
  }
 ]
}