== Introduction

This tutorial builds two Java services from scratch that incrementally add Eclipse MicroProfile APIs. The first is a `student` service that returns a list of students, which is invoke by a `frontend` service. This domain model is simple so the focus is spent on the MicroProfile APIs themselves.

The documented steps in this tutorial follow a pattern:

. Write code
. Run a command to test code (curl)
. Check output

This pattern flows quickly due to Quarkus' Live Coding feature, and makes checking code changes near-instantaneous so each change can be immediately evaluated.

NOTE: This tutorial will require three terminal windows. Each command block will display the terminal where the command is to be run - _Terminal 1_, _Terminal 2_, or _Terminal 3_. As the tutorial progresses, it helps to organize the terminals on your screen so they can all be viewed at the same time. In addition, each code block will show the name of the file to be edited (ex: "StudentResource.java")

== Minimum Requirements

. Java 8, 11, 12, 13, or 14
. Native compilation - GraalVM 19.3.1 or 20.0.0
.. Assign at least 4GB RAM and 2 vcpu to your Docker VM
.. ... or be very, very patient
. Maven 3.6.2+

== Setup Local Repository

. Clone the project to your local system
+
--
.Terminal 1
----
$ git clone \
  https://github.com/jclingan/oreilly-microprofile-tutorial.git \
  tutorial
----
.Terminal 1 Output
....
Cloning into 'tutorial'...
remote: Enumerating objects: 130, done.
remote: Counting objects: 100% (130/130), done.
remote: Compressing objects: 100% (92/92), done.
remote: Total 130 (delta 29), reused 120 (delta 22), pack-reused 0
Receiving objects: 100% (130/130), 2.50 MiB | 644.00 KiB/s, done.
Resolving deltas: 100% (29/29), done.
....
--
