== MicroProfile Fault Tolerance

This section will utilize fault tolerance patterns in the frontend service to handle problematic conditions caused by the student service.

. Add a timeout to `FrontendResource.listStudents()`
+
--
.FrontendResource.java
[source,java]
----
@Timeout  <1>
@GET
@Path("/list")
@Produces(MediaType.APPLICATION_JSON)
public List<String> listStudents() {
    List<String> students = student.listStudents();
    
    return students;
}
----
<1> Add `@Timeout` annotation, which defaults to 1000ms
--
+
// *********************************************
'''
. Check endpoint. Verify `org.eclipse.microprofile.faultolerance.exceptions.TimeoutException` is thrown.
+
--
.Terminal 3
[source,bash]
----
$ curl -i localhost:8080/frontend/list
----
.Terminal 3 Output
....
# Stack trace ...
org.jboss.resteasy.spi.UnhandledException: org.eclipse.microprofile.faulttolerance.exceptions.TimeoutException: Timeout[org.acme.FrontendResource#listStudents] timed out
# Stack trace ...
....
.Terminal 2 Output
....
# Stack trace ...
org.jboss.resteasy.spi.UnhandledException: org.eclipse.microprofile.faulttolerance.exceptions.TimeoutException: Timeout[org.acme.FrontendResource#listStudents] timed out
# Stack trace ...
....

.Terminal 1 Output
....
** Waiting 2000ms **
....
--
+
// *********************************************
'''

. Add a src/main/java/org/acme/ListStudentsFallbackHandler.java fallback class to provide alternative logic when an exception is thrown
+
--
.ListStudentsFallbackHandler.java
[source,java]
----
package org.acme;

import java.util.Arrays;
import java.util.List;

import javax.inject.Inject;

import org.eclipse.microprofile.faulttolerance.ExecutionContext;
import org.eclipse.microprofile.faulttolerance.FallbackHandler;
import org.eclipse.microprofile.metrics.MetricRegistry;
import org.eclipse.microprofile.metrics.MetricRegistry.Type;
import org.eclipse.microprofile.metrics.annotation.RegistryType;

/*
   A fallback handler has access to the ExecutionContext, which can
   be used to determine where the failure originated (class and method)
   and the cause of the failure

   Print the cause of the failure to stdout, and return a list of "top students"
*/

public class ListStudentsFallbackHandler implements FallbackHandler<List<String>> {
    @Inject
    @RegistryType(type = Type.APPLICATION)
    MetricRegistry registry;

    @Inject
    CircuitBreakerTracker tracker;

    @Override
    public List<String> handle(ExecutionContext ctx) {
        List<String> students = Arrays.asList("Smart Sam", "Genius Gabby", "A-Student Angie", "Intelligent Irene");
        String failure;

        registry.counter("listStudentsCounter").inc();

        if (ctx.getFailure() == null) {
            failure = "unknown";
        } else {
            failure = ctx.getFailure().getMessage();
        }

        System.out.println("Exception " + failure);
        System.out.println("listStudentsFallbackCounter: " + registry.counter("ft.org.acme.FrontendResource.listStudents.fallback.calls.total").getCount());

        return students;
    }
}
----
--
+
// *********************************************
'''
. Call fallback method when an exception is thrown
+
// *********************************************
'''

. Call the fallback method to provide alternative logic when an exception is thrown
+
--
.FrontendResource.java
[source,java]
----
@Fallback(value = ListStudentsFallbackHandler.class) <1>
@Timeout
@GET
@Path("/list")
@Produces(MediaType.APPLICATION_JSON)
public List<String> listStudents() {
    List<String> students = student.listStudents();
    
    return students;
}
----
<1> Add `@Fallback` annotation
--
+
// *********************************************
'''
. Check endpoint. Verify the fallback student list is retrieved
+
--
.Terminal 3
[source,bash]
----
$ curl -i localhost:8080/frontend/list
----

.Terminal 2 Output
....
Exception Timeout[org.acme.FrontendResource#listStudents] timed out
listStudentsFallbackCounter: 1
....

.Terminal 3 Output
....
HTTP/1.1 200 OK
Content-Length: 66
Content-Type: application/json

["Smart Sam","Genius Gabby","A-Student Angie","Intelligent Irene"]
....

.Terminal 1 Output
....
** Waiting 2000ms **
....
--
+
// *********************************************
'''

. Disable all fault tolerance annotations (except `@Fallback`). Useful for when running in a service mesh (e.g. Istio) environment. Commenting out any one of the timeout-disabling properties will disable the timeout.
+
--
.frontend microprofile-config.properties
[source,properties]
----
# Disable fault tolerance globally
MP_Fault_Tolerance_NonFallback_Enabled=false <1>

# Disable group policy:
#Timeout/enabled=false

# Disable a specific fault tolerance policy. Ex:
#org.acme.FrontendResource/listStudents/Timeout/enabled=false
----
<1> All fault tolerance annotations disabled because this annotation is not commented out
--
+
// *********************************************
'''

. Check that original list of students is returned
+
--
.Terminal 3
[source,bash]
----
$ curl -i localhost:8080/frontend/list
----

.Terminal 3 Output
....
HTTP/1.1 200 OK
Content-Length: 41
Content-Type: application/json

["Duke","John","Jane","Arun","Christina"]
....

.Terminal 1 Output
....
** Waiting 2000ms **
....
--
+
// *********************************************
'''

. Comment out `MP_Fault_Tolerance_NonFallback_Enabled=false` in `microprofile-config.properties`
+
--
.frontend microprofile-config.properties
[source,properties]
----
# Disable fault tolerance globally
#MP_Fault_Tolerance_NonFallback_Enabled=false <1>

# Disable group policy:
#Timeout/enabled=false

# Disable a specific fault tolerance policy. Ex:
#org.acme.FrontendResource/listStudents/Timeout/enabled=false
----
<1> Commented out

NOTE: Feel free to uncomment the more specific approaches (all timeouts or just the timeout on `listStudents()`) and try them out. Just remember to comment them all out before continuing beyond this step.

--
+
// *********************************************
'''

. External configuration of fault tolerance parameters. 
+
--

NOTE: MicroProfile Fault Tolerance allows any fault tolerance annotation parameter to be configured in microprofile-config.properties, overriding the value in source code. 

.frontend microprofile-config.properties
[source,properties]
----
...
...
#org.acme.FrontendResource/listStudents/Timeout/enabled=false
org.acme.FrontendResource/listStudents/Timeout/value=3000 <1>
----
<1> Add this, making the timeout longer than the wait time and preventing the fallback from being called.

.Terminal 3
[source,bash]
----
$ curl -i localhost:8080/frontend/list
----
.Terminal 3 Output
....
HTTP/1.1 200 OK
Content-Length: 41
Content-Type: application/json

["Duke","John","Jane","Arun","Christina"]
....

.Terminal 1 Output
....
** Waiting 2000ms **
....
--
// *********************************************
'''

. Comment out timeout value in `microprofile-config.properties` so annotation parameter values are used
+
--
.frontend microprofile-config.properties
[source,properties]
----
...
...
#org.acme.FrontendResource/listStudents/Timeout/enabled=false
#org.acme.FrontendResource/listStudents/Timeout/value=3000 <1>
----
<1> Comment this out

--

+

// *********************************************
'''

. Check endpoint. Verify fallback list of students is retrieved
+
--
.Terminal 3
[source,bash]
----
$ curl -i localhost:8080/frontend/list
----

.Terminal 2 Output
....
Exception Timeout[org.acme.FrontendResource#listStudents] timed out
listStudentsFallbackCounter: 2
....

.Terminal 3 Output
....
HTTP/1.1 200 OK
Content-Length: 66
Content-Type: application/json

["Smart Sam","Genius Gabby","A-Student Angie","Intelligent Irene"]
....

.Terminal 1 Output
....
** Waiting 2000ms **
....
--
+
// *********************************************
'''

. Update doDelay() in StudentResource.java to return a random delay.
+
--
.StudentResource.java
[source,java]
----
void doDelay() {
    int delayTime;
    try {
        delayTime=(int)(Math.random()*delay); <1>
        System.out.println("** Waiting " + delayTime + "ms **");
        TimeUnit.MILLISECONDS.sleep(delayTime);
    } catch (InterruptedException e) {
        e.printStackTrace();
    }
}
----
<1> Updated code to print random number: `delayTime=(int)(Math.random()*delay);`
--
+
// *********************************************
'''

. Verify random sleep time.
+
--
.Terminal 3
[source,bash]
----
$ curl -i localhost:8080/frontend/list
----
.Terminal 2 Output
....
# Depending on random timeout, may show:
Exception Timeout[org.acme.FrontendResource#listStudents] timed out
listStudentsFallbackCounter: 3
....

.Terminal 3 Output
....
HTTP/1.1 200 OK
Content-Length: 66
Content-Type: application/json

["Smart Sam","Genius Gabby","A-Student Angie","Intelligent Irene"]
or
["Duke","John","Jane","Arun","Christina"]                   
....

NOTE: Because the delay is random, a longer delay will return the fallback student list, and a shorter delay will return the original student list.

.Terminal 1 Output
....
** Waiting 1-1000ms ** <1>
....
<1> This will be a random number between 1 and 1000

NOTE: Retry a few times to see random sleep times. Keep retrying until Timeout threshold is reached and fallback method is called.
--
+
// *********************************************
'''

. Add a @Retry annotation, which by default will retry a request up to 3 times when exception is caught (e.g. TimeoutException)
+
--
.FrontendResource.java
[source,java]
----
@Timeout
@Retry  <1>
@Fallback(value = ListStudentsFallbackHandler.class)
@GET
@Path("/list")
@Produces(MediaType.APPLICATION_JSON)
public List<String> getStudents() {
    List<String> students = student.listStudents();
    
    return students;
}
----
<1> Add this
--

+
// *********************************************
'''

. Check retry logic
+
--
.Terminal 3
[source,bash]
----
$ curl -i localhost:8080/frontend/list
----
.Terminal 2 Output
....
# Depending on random timeout, may show:
Exception Timeout[org.acme.FrontendResource#listStudents] timed out
listStudentsFallbackCounter: 4
....

.Terminal 3 Output
....
HTTP/1.1 200 OK
Content-Length: 66
Content-Type: application/json

["Smart Sam","Genius Gabby","A-Student Angie","Intelligent Irene"]
or
["Duke","John","Jane","Arun","Christina"]                               
....

.Terminal 1 Output
....
** Waiting 1-1000ms ** <1>
....
<1> One line will be displayed if less than 500ms, more than one line if more than 500ms due to retry

NOTE: Re-run command until there are at least two output lines in Terminal 1 for a single `curl` command, at least one of which will be more than 500ms.
--
+
// *********************************************
'''

. Create file src/main/java/org/acme/CircuitBreakerTracker.java
+
--

This class will be used to track the state of our upcoming circuitbreaker. It will print the state of the circuitbreaker to stdout.

.CircuitBreakerTracker.java
[source,java]
----
package org.acme;

import java.time.Duration;
import java.util.HashMap;
import java.util.Map;

import javax.enterprise.context.Dependent;
import javax.inject.Inject;

import org.eclipse.microprofile.metrics.Gauge;
import org.eclipse.microprofile.metrics.MetricID;
import org.eclipse.microprofile.metrics.MetricRegistry;
import org.eclipse.microprofile.metrics.MetricRegistry.Type;
import org.eclipse.microprofile.metrics.annotation.RegistryType;

@Dependent
public class CircuitBreakerTracker {
    @Inject
    @RegistryType(type = Type.APPLICATION)
    MetricRegistry registry;

    public Map<String, String> track() {
        HashMap<String, String> map = new HashMap<>();
        MetricID id = new MetricID("ft.org.acme.FrontendResource.listStudents.circuitbreaker.closed.total");
        Gauge gauge = registry.getGauges().get(id);

        if (gauge != null) {
            map.put("CBClosedTime", "" + Duration.ofNanos((long) gauge.getValue()).toMillis() + "ms\n");
        }

        id = new MetricID("ft.org.acme.FrontendResource.listStudents.circuitbreaker.halfOpen.total");
        gauge = registry.getGauges().get(id);
        if (gauge != null) {
            map.put("CBHalfOpenTime", "" + Duration.ofNanos((long) gauge.getValue()).toMillis() + "ms\n");
        }

        id = new MetricID("ft.org.acme.FrontendResource.listStudents.circuitbreaker.open.total");
        gauge = registry.getGauges().get(id);
        if (gauge != null) {
            map.put("CBOpenTime", "" + Duration.ofNanos((long) gauge.getValue()).toMillis() + "ms\n");
        }

        map.put("CBSucceededCount",
                "" + registry.counter("ft.org.acme.FrontendResource.listStudents.circuitbreaker.callsSucceeded.total")
                        .getCount() + "\n");
        map.put("CBPreventedCount",
                "" + registry.counter("ft.org.acme.FrontendResource.listStudents.circuitbreaker.callsPrevented.total")
                        .getCount() + "\n");

        map.forEach((key, value) -> System.out.print(key + ": " + value));
        System.out.println();

        return map;

    }
}
----
--
+
// *********************************************
'''

. Replace `@Timeout` logic with a `@CircuitBreaker`
+
--
.FrontendResource.java
[source,java]
----
// @Timeout                         <1>
// @Retry                           <2>
@CircuitBreaker(                    <3>
    requestVolumeThreshold = 4,     <4>
    failureRatio = 0.5,             <5>
    delay = 10000,                  <6>
    successThreshold = 2            <7>
    )
@Fallback(value = ListStudentsFallbackHandler.class)
@GET
@Path("/list")
@Produces(MediaType.APPLICATION_JSON)
public List<String> getStudents() {
    List<String> students = student.listStudents();
    
    return students;
}
----
<1> Comment out @Timeout
<2> Comment out @Retry
<3> Add a circuit breaker. If circuit breaker throws a CircuitBreakerOpen exception, the @Retry annotation will retry the request.
<4> Rolling window of 4 requests.
<5> % of failures within the window that cause the circuit breaker to transition to "open"state
<6> Wait 1000 milliseconds before allowing another request. Until then, each request will result in a CircuitBreakerOpen exception
<7> Number of consecutive successful requests before circuit transitions from the half-open state to the closed state. The circuit breaker enters the half-open state upon the first successful request.
--
+
// *********************************************
'''

. Inject the CircuitbreakerTracker instance in FrontendResource.java
+
--
.FrontendResource.java
[source,java]
----
@Path("/frontend")
public class FrontendResource {
    @Inject                          <1>
    CircuitBreakerTracker tracker;

    @Inject
    @RestClient
    StudentRestClient student;
----
<1> Inject an instance of the circuitbreaker tracker
--
+
// *********************************************
'''
. Output circuit breaker stats
+
--
.FrontendResource.java
[source,java]
----
List<String> students;

tracker.track(); <1>

students = student.listStudents();
----
<1> Display the circuitbreaker state
--
+
// *********************************************
'''

. Inject the CircuitbreakerTracker instance in ListStudentsFallbackHandler.java
+
--
.ListStudentsFallbackHandler.java
[source,java]
----
@Inject
@RegistryType(type = Type.APPLICATION)
MetricRegistry registry;

@Inject                         <1>
CircuitBreakerTracker tracker;
----
<1> Inject the tracker 
--
+
// *********************************************
'''
. Output circuit breaker stats in ListStudentsFallbackHandler.java
+
--
.ListStudentsFallbackHandler.java
[source,java]
----
System.out.println("Exception " + failure);
System.out.println("listStudentsFallbackCounter: " + registry.counter("ft.org.acme.FrontendResource.listStudents.fallback.calls.total").getCount());
tracker.track();  <1>
----
<1> Display the circuitbreaker state
--
+

// *********************************************
'''

. Check CircuitBreaker logic
+
--
.Terminal 3
[source,bash]
----
$ curl -i localhost:8080/frontend/list
----
.Terminal 3 Output
....
HTTP/1.1 200 OK
Content-Length: 66
Content-Type: application/json

["Duke","John","Jane","Arun","Christina"]                               
....


.Terminal 2
[source,bash]
----
CBClosedTime: 4ms        <1>
CBOpenTime: 0ms          <2>
CBSucceededCount: 0      <3>
CBPreventedCount: 0      <4>
CBHalfOpenTime: 0ms      <5>
----
<1> Amount of time circuitbreaker is in the closed state
<2> Amount of time circuitbreaker is in the open state
<3> Number of times a call is successfully completed
<4> Number of times a call was prevented due to circuit breaker being open
<5> Amount of time circuitbreaker is in the half-open state

.Terminal 1 Output
....
** Waiting 1-1000ms **
....
--
+

// *********************************************


. Stop student service
+
--
.Terminal 1
[source,bash]
----
CTRL-C
----
--
+
// *********************************************
'''

. Check the circuit breaker
+
--

This will result in `java.net.ConnectException`. When circuit breaker delay is exceeded, then the circuit breaker throws a CircuitBreakerOpenException. Both exceptions are caught by fallback logic to invoke fallback method. Try running this a few times, waiting 10-15 seconds occasionally.


.Terminal 3
[source,bash]
----
$ curl -i localhost:8080/frontend/list
----

.Terminal 2
[source,bash]
----
Exception RESTEASY004655: Unable to invoke request: java.net.ConnectException: Connection refused (Connection refused)
listStudentsFallbackCounter: 1
CBClosedTime: 6770ms
CBOpenTime: 0ms
CBSucceededCount: 1
CBPreventedCount: 0
CBHalfOpenTime: 0ms
----

.Terminal 1
[source,bash]
----
** Waiting 844ms **
----
--
+
// *********************************************
'''

. Re-run student service
+
--
.Terminal 1
[source,bash]
----
mvn compile quarkus:dev -Ddebug=5006
----
--
+
// *********************************************
'''

. Retry until circuit breaker closes and the normal student list is displayed.
+
--
.Terminal 3
[source,bash]
----
$ curl -i localhost:8080/frontend/list
----

.Terminal 3 Output
....
HTTP/1.1 200 OK
Content-Length: 66
Content-Type: application/json

["Smart Sam","Genius Gabby","A-Student Angie","Intelligent Irene"]
....
--
Retry the command until the primary student list is displayed. During this time, you will see changes to the stats output to the CLI.

Example:

.Terminal 2
....
CBClosedTime: 25202ms
CBOpenTime: 28069ms
CBSucceededCount: 4
CBPreventedCount: 3
CBHalfOpenTime: 19369ms
....
